import turtle as t

# ##################### Bild 1 (Stern)
# t.hideturtle()
# t.color('green', 'blue')
# for runde in range(80):
#     t.forward(200)
#     t.left(170)
# t.clearscreen()

# ##################### Bild 2 (Herz)
t.hideturtle()
t.width(5)
t.color('red', 'red')
t.begin_fill()
angle = 30
factor = 3
t.left(90 - angle)
t.forward(80 * factor)
t.left(angle)
t.circle(20 * factor, 180)
t.right(180)
t.circle(20 * factor, 180)
t.left(angle)
t.forward(80 * factor)
t.end_fill()
#t.clearscreen()

# ##################### Bild 3 (Pacman)
# t.hideturtle()
# t.color('yellow', 'yellow')
# t.begin_fill()
# t.left(90 - 45)
# t.forward(150)
# t.left(90)
# t.circle(150, 180 + 90)
# t.left(90)
# t.forward(150)
# t.end_fill()
# t.color("white")
# t.right(45+90)
# t.forward(200)
# t.color("black")
# t.right(90)
# t.circle(10)

# ##################### Bild 4 - Olympische Ringe
# t.width(10)
# t.color('blue')
# t.circle(100)
# t.up()
# t.color('black')
# t.forward(220)
# t.down()
# t.circle(100)
# t.up()
# t.color('red')
# t.forward(220)
# t.down()
# t.circle(100)
# t.up()
# t.color('green')
# t.right(90)
# t.forward(10)
# t.right(90)
# t.forward(10)
# t.right(90)
# t.down()
# t.circle(100, 360 + 180)
# t.up()
# t.color('yellow')
# t.right(90)
# t.forward(20)
# t.right(90)
# t.down()
# t.circle(100)

#t.done()
