import turtle

# ##################### Bild 1 (Stern)
# turtle.hideturtle()
# turtle.color('green', 'blue')
# for runde in range(80):
#     turtle.forward(200)
#     turtle.left(170)
# turtle.clearscreen()

# ##################### Bild 2 (Herz)
turtle.hideturtle()
turtle.width(5)
turtle.color('red', 'red')
turtle.begin_fill()
angle = 30
factor = 3
turtle.left(90 - angle)
turtle.forward(80 * factor)
turtle.left(angle)
turtle.circle(20 * factor, 180)
turtle.right(180)
turtle.circle(20 * factor, 180)
turtle.left(angle)
turtle.forward(80 * factor)
turtle.end_fill()
#turtle.clearscreen()

# ##################### Bild 3 (Pacman)
# turtle.hideturtle()
# turtle.color('yellow', 'yellow')
# turtle.begin_fill()
# turtle.left(90 - 45)
# turtle.forward(150)
# turtle.left(90)
# turtle.circle(150, 180 + 90)
# turtle.left(90)
# turtle.forward(150)
# turtle.end_fill()
# turtle.color("white")
# turtle.right(45+90)
# turtle.forward(200)
# turtle.color("black")
# turtle.right(90)
# turtle.circle(10)

# ##################### Bild 4 - Olympische Ringe
# turtle.width(10)
# turtle.color('blue')
# turtle.circle(100)
# turtle.up()
# turtle.color('black')
# turtle.forward(220)
# turtle.down()
# turtle.circle(100)
# turtle.up()
# turtle.color('red')
# turtle.forward(220)
# turtle.down()
# turtle.circle(100)
# turtle.up()
# turtle.color('green')
# turtle.right(90)
# turtle.forward(10)
# turtle.right(90)
# turtle.forward(10)
# turtle.right(90)
# turtle.down()
# turtle.circle(100, 360 + 180)
# turtle.up()
# turtle.color('yellow')
# turtle.right(90)
# turtle.forward(20)
# turtle.right(90)
# turtle.down()
# turtle.circle(100)

turtle.done()
